G-Node/nixpy

nix/test/test_source.py, nix/util/proxy_list.py
to avoid code like this
````
array.sources.append(source1)
array.sources.append(source2)
````
RefProxyList got an extend method that appends a list of elements
````
array.sources.extend([source1, source2])
````
Regarding the test case: I put it into the TestSources, probably not the perfect place. so let me know where you would prefer it.
=> RefProxyList got an extend method much like lists have 

.gitignore, setup.py, src/PyEntity.hpp, src/PyExceptions.cpp, src/core.cc
Related by Ajays bug report #114: On the nix side the exceptions are correctly thrown, with correct messages etc. On the nixpy side they sometimes loose the messages. 
I explicitly wrapped the nix exceptions to python exceptions checking for empty messages and, in these instances, giving "standard" error messages.  
It is kind of ugly but works.
=> Exceptions wrapper

nix/test/test_util.py, src/PyUtil.cpp, src/docstrings.cpp, src/docstrings.hpp
adapt test for split_compound_unit to the fix in the nix lib.
Add docstrings for util methods
=> Util::split_compound fix and doc strings

README.md, nix/__init__.py, nix/block.py, nix/data_array.py, nix/entity_with_sources.py, nix/file.py, nix/multi_tag.py, nix/property.py, nix/section.py, nix/source.py, nix/tag.py, nix/test/test_data_array.py, nix/test/test_proxy_list.py, nix/util/inject.py, nix/util/proxy_list.py, setup.py, src/PyDataSet.cpp, src/PyEntity.hpp, src/PyValue.cpp, src/transmorgify.hpp
Here are a few changes needed to make nixpy work with python3.
One major change - we cannot use metaprogramming to inject methods as elegant as before (see "The Metaclass Hook in Python 3" here http://python-3-patterns-idioms-test.readthedocs.org/en/latest/Metaprogramming.html). So I used the easy solution and monkey patch classes directly (could be easily changed later if you'd like).
All tests run fine EXCEPT 2 TESTS in data set. Something is wrong with indexing ("selection+offset not within extent"). It would be nice if someone who developed DataSet could take a look and fix these.
Other than that it should be fine.
=> Python3 compatibility

src/PyDataSet.cpp, src/PyEntity.hpp
As @jgrewe detected in pr #124 there is a small build warning
since we don't actually return a value in PyDataSet::do_export
for py3.
=> Fix small py3 related build warning

docs/source/overview.rst
-nix.DataArray.dtype has no object named Double
-nix.DataType.Double is valid , so I think `dtype=nix.dtype.Double` must be changed to `dtype=nix.DataType.Double`
bec. command was giving the AttributeError.
=> changed the dtype in overview.rst

docs/source/overview.rst
-fixed typos
- `tag.references.add(data)` throws AttributeError , fixed with `tag.references.extend(data)` 
- `np.rando.randn` requires integer ,so fixed
-`np.zeros((3,2))` required
=> fixed python code block in overview.rst

nixio/pycore/file.py
Backend now defaults to HDF5 if it is available and H5Py if it is not.
Error is raised only when HDF5 is explicitly selected and unavailable.
=> Smarter default backend

nixio/pycore/block.py, nixio/pycore/entity_with_metadata.py, nixio/pycore/entity_with_sources.py, nixio/pycore/feature.py, nixio/pycore/file.py, nixio/pycore/group.py, nixio/pycore/h5group.py, nixio/pycore/section.py, nixio/pycore/source.py, nixio/pycore/tag.py, nixio/pycore/util/names.py, nixio/pycore/util/util.py, nixio/test/test_group.py, nixio/util/find.py
Added two new tests for containers nested under Group, i.e., `data_arrays`, `multi_tags`, and `tags`.
1. Get by name
Retrieving from these containers by name in pycore would fail. Items in these containers are links, referenced by entity ID instead of name. The getter functions have been fixed to account for this.
The new test creates a number of objects, adds them to the group, and then retrieves them by name.
2. Invalid append
Appending to these containers would succeed even when the object being added was not a child of the same parent Block as the Group. In other words, inter-block references were being allowed by nixpy which is not allowed in the NIX specification.
The new test creates a second block with a group and attempts to add children of the first block to the group under the …
=> [PyCore] Bug fixes

nixio/pycore/entity_with_metadata.py, nixio/pycore/file.py, nixio/pycore/h5group.py, nixio/pycore/section.py, nixio/test/test_backend_compatibility.py, nixio/test/test_section.py
Section constructor now accepts parent section and keeps a reference. When accessing a section through an object's `.metadata` reference, the Section is found by searching the file's metadata tree in order to return an object with the correct parent reference.
This PR also includes a restructuring of the File creation and open methods, which is unrelated to the fix described above.
Fixes #174.
=> Section.parent fix

.gitignore, .travis.yml, checknix.py, nixio/test/test_backend_compatibility.py, setup.py
Setup script updated to support building without the NIX dependency.
The setup script detects if NIX is available by attempting to compile a dummy C++ file that simply imports `nix.hpp` and checking if it fails (see new file `checknix.py`).
Additionally, Python only builds can now be explicitly performed using `python setup.py build --pyonly`.
Travis build config now includes 4 configurations: Python 2.7 and 3.4 with and without NIX.
=> Python only builds

appveyor.yml, checknix.py, findboost.py, nixio/__init__.py, setup.py
Regarding wheels, this works by getting the most recent nix (currently the version is set using `NIX_VERSION` in appveyor) binaries and including them in the wheel. It adds them under share/nixio/bin in your python installation folder. Then at runtime that folder, if it exists, is added to the PATH.
This is how we do it at [kivy ](https://github.com/kivy/kivy) and is similarly how numpy [does it](https://github.com/numpy/numpy/issues/6923) (although a bit differently). This makes it easy to install and uninstall since you just need to do pip install wheel_name, provided you have the numpy and h5py dependencies installed of course. If it's uploaded to pypi, then they just do `pip install nixio`.
When packaging and building a end user exe using e.g. pyinstaller, for projects that use nixio, …
=> Windows: Add wheel and appveyor support

appveyor.yml, findboost.py
This will fix the macOS compile bug (issue #218). Hopefully not break win or GNU/Linux.
I actually haven't verified the other changes that were done with PR #217 just made sure
it is working on macOS again.
=> findboost: detect win lib via ext == ".lib"

nixio/value.py
This change is necessary for [Neo](https://github.com/NeuralEnsemble/python-neo/blob/master/neo/io/nixio.py) to save a nix file. Specific use case was saving a Neo block loaded from a Blackrock .nev file.
```
data_block = neo.io.BlackrockIO(file_name, verbose=False).read_block(name=file_name,
nsx_to_load=None,
channels='all',
units='all',
load_waveforms=False,
load_events=True,
lazy=False,
cascade=True)
writer = neo.io.NixIO(filename='b.nix', mode="ow")
writer.write_block(data_block)
```
=> Adds bools to valid_types

nixio/pycore/util/util.py
Currently, when simply creating a file, e.g. with `f = nix.File.open(file_name, nix.FileMode.Overwrite)` I get the following error:
```
Traceback (most recent call last):
File "G:\Python\libs\Playground\src\nix.py", line 6, in <module>
f = nix.File.open(file_name, nix.FileMode.Overwrite)
File "E:\Python27_x64\lib\site-packages\nixio\pycore\file.py", line 130, in open
return cls._open(path, mode)
File "E:\Python27_x64\lib\site-packages\nixio\pycore\file.py", line 101, in _open
newfile = cls._create_new(path, h5mode)
File "E:\Python27_x64\lib\site-packages\nixio\pycore\file.py", line 83, in _create_new
newfile = cls(h5file)
File "E:\Python27_x64\lib\site-packages\nixio\pycore\file.py", line 64, in __init__
self.force_created_at()
File …
```
=> Fix "Invalid format string" error in now_int

nixio/__init__.py
If nixio is imported before the binaries are added to path the hdf5 backend doesn't work and instead h5py is used.
=> Add bins to path early

.travis.yml, README.rst, appveyor.yml, findboost.py, nixio/__init__.py, nixio/file.py, nixio/pycore/exceptions/exceptions.py, nixio/pycore/file.py, nixio/pycore/section.py, nixio/test/test_backend_compatibility.py, nixio/test/test_file.py, setup.py, src/PyDataSet.cpp, src/PyProperty.cpp
Counterpart to G-Node/nix#638.
Compares supported file version with the format version of the file being opened and decides whether it can be opened in the requested mode (read only or read write).
Follows the [NIX documentation on versioning](https://github.com/G-Node/nix/blob/master/docs/versioning.md).
=> Version compatibility checks

.travis.yml, README.rst, appveyor.yml, findboost.py, nixio/__init__.py, nixio/file.py, nixio/pycore/section.py, nixio/test/test_backend_compatibility.py, setup.py, src/PyDataSet.cpp, src/PyProperty.cpp
Major cleanup of appveyor build configuration.
- Use Miniconda for h5py.
- Use latest build NIX from Appveyor.
- Run tests.
- Build Windows wheels for distribution.
- *Ignore failures when building against NIX C++ backend.*
=> Appveyor builds

setup.py
Simplify the imports of the nixpy project information attributes like `AUTHOR`, `VERSION`, `CONTACT` , etc. in `setup.py` .
The implemented way is simpler than matching `regex` from the `info.py` file data.
Please review.
=> Simplify project attributes imports in setup.py

docs/source/install.rst
Previously link is anchored to `README.md` but project contains `README.rst`.
=> Fixed a broken link

nixio/__init__.py
Closing #242.
Added `__version__` attribute.
```python
>>> import nixio as nix
>>> nix.__version__
'1.3dev'
```
And I see that `__author__` attribute is defined in `nixio/__init__.py` and `info.py` separately. But we can import it from `info.py` as I did for `__version__`. Any comments?
=> Added version attribute

nixio/pycore/h5dataset.py
Datasets with empty shape or 0 in any dimension break h5py.
We just return the empty array when there's such data.
=> [h5dataset] Fix for reading empty datasets

nixio/pycore/entity_with_metadata.py, nixio/pycore/section.py
Instead of setting the parent link on access, which triggers a search every time a Section is instantiated, do it only on demand, when the parent property is requested.
Previously, the section parent link was set when accessing an object's metadata property. This is a problem when working with an object's metadata since every time something like `block.metadata` was accessed, it would run a search for the parent. Also, accessing the parent section is probably not very common task to begin with.
Now, the search is performed only when necessary.
The following script shows how the timings change:
```python
import nixio as nix
from uuid import uuid4
from timeit import timeit
def create_deep_metadata(nixfile):
block = nixfile.blocks[0]
block.metadata = nixfile.create_section(uuid4().hex, "s") …
```
=> [Section.parent] BFS to find on demand

nixio/pycore/multi_tag.py, nixio/pycore/tag.py, nixio/test/test_multi_tag.py, nixio/test/test_tag.py, src/PyMultiTag.cpp, src/PyTag.cpp
Counterpart to G-Node/nix#669.
Handles retrieving data and references by name in Tags and MultiTags in both PyCore and the NIX bindings.
Includes tests for retrieving data by name.
=> Retrieve data overloads

nixio/pycore/file.py
If no backend has been set in code we can overwrite the default
backend via the NIXPY_H5_BACKEND env variable. Useful for testing
scripts/code against both backends without modifying existing
code.
NB: relies on os.getenv to return NONE for unknown variables, which
it should for both 2.7 and 3.
=> Add NIXPY_H5_BACKEND for runtime backend selection

nixio/pycore/dimensions.py, nixio/pycore/file.py, nixio/pycore/h5group.py, nixio/pycore/multi_tag.py, nixio/pycore/tag.py, nixio/test/test_file.py, nixio/test/test_multi_tag.py, nixio/test/test_tag.py, setup.py
Fixed the order tracking issue. The iteration order was set to `NATIVE` instead of `INC`(reasing).
This PR includes the header changes from PR #266 and fixes the issue (tested locally for combinations of python2 and python3).
It also PARTIALLY includes PR #263, but the issue is not completely resolved yet.
=> FIXES: Order tracking, (Multi)Tag.retrieve_data, and header format string type

.travis.yml, nixio/pycore/data_array.py, nixio/pycore/dimensions.py, nixio/pycore/file.py, nixio/test/test_backend_compatibility.py, nixio/test/test_block.py, nixio/test/test_data_array.py, nixio/test/test_dimensions.py, nixio/test/test_feature.py, nixio/test/test_file.py, nixio/test/test_group.py, nixio/test/test_multi_tag.py, nixio/test/test_property.py, nixio/test/test_section.py, nixio/test/test_source.py, nixio/test/test_tag.py, setup.cfg, src/PyFile.cpp
This PR is primarily to fix the handling of Alias Range Dimensions in pycore but also includes some other cleanup and maintenance changes.
The alias dimension handling wasn't creating a link to the data array as specified by the NIX specification. Instead it was making a copy and so the two backends were behaving differently and has this small incompatibility.
Here's a nice script that creates a file with an alias dimension using both backends and then compares them using vimdiff:
```bash
#!/usr/bin/env bash
cat > createaliasdim.py << EOF
import nixio as nix
import numpy as np
import sys
writer = sys.argv[1]
event_times = np.array([1, 2, 3, 5, 8, 13, 21])
f = nix.File.open("alias_test.nix", nix.FileMode.Overwrite, writer)
b = f.create_block("test", "test")
da = b.create_data_array("the …
```
=> FIX Alias Range Dimension handling

.gitignore, nixio/data_array.py, nixio/test/test_data_array.py
Fix for issue #273.
When reading a DataArray, a numpy array is allocated with a data type that matches the DataArray. When the DataArray has polynomial coefficients defined and the resulting values of applying the coefficients to the raw data is outside the domain of the data type, the data values are truncated.
A data array with *Integer* dtype, internal value `[11]`, and polynomial coefficients `(0, 0.1)` will return the integer value `1` instead of `1.1`.
Always return numpy arrays of type `float64` when a DataArray has any polynomial coefficients defined.
---
I'd be interested to know if anyone thinks we could be smarter about this. For instance, should we be testing if both data and coefficients are integers and not change the type?
=> Fix for value truncation when applying polynomial coefficients

.gitignore, nixio/pycore/tag.py, nixio/test/test_backend_compatibility.py, nixio/test/test_multi_tag.py, nixio/test/test_tag.py
Followup to #259 (counterpart to G-Node/nix#669).
Adds tests for:
- Retrieving a Tag and MultiTag reference by the reference ID or name
- Retrieving a Tag and MultiTag feature by the linked DataArray ID or name
- Calling the retrieve_data function using the DataArray ID or name
Fixes:
- Feature getter did not allow accessing elements by DataArray ID or name
- Tag.retrieve_data function raised error when called with reference ID or name
Closes #279
=> Retrieve feature and reference data by name or ID

nixio/pycore/data_array.py, nixio/pycore/dimensions.py, nixio/pycore/exceptions/exceptions.py, nixio/pycore/property.py, nixio/test/test_data_array.py, nixio/test/test_property.py, src/PyExceptions.cpp
This PR:
- Allows any string to be set as a unit for Properties
- Allows any string to be set as a unit for DataArrays except when the DataArray has an AliasRangeDimension
- Checks are performed both when setting a unit (checks for SI only if the DataArray has an AliasRangeDimension) and when adding an AliasRangeDimension (checks if the existing unit is SI)
- Sets a Property's or DataArray's unit to `None` if the unit is set to an empty string or a string that is only spaces.
Closes #278 and #269.
=> Allow non-SI units in Properties and DataArrays

.travis.yml, MANIFEST.in, nixio/info.json, nixio/info.py, scripts/dorelease.py, setup.py
In the olden days, we had the `setup.py` parse the `info.py` with regular expressions to get the info.
At some point I changed this to a simple import, that worked as long as the package was installed using `pip install [...]` but failed if it was installed using `python setup.py install` and the system was missing any of the dependencies. This is because the setup essentially depended on importing the package itself and couldn't start the install process without importing the sources.
With this PR, we change both the `setup.py` and `info.py` to read the information from a JSON file that's packaged with the source files.
<details>
<summary>Tested working using the following Dockerfile (click to expand)</summary>
```dockerfile
FROM debian:buster-slim
RUN apt update
RUN apt install -y …
```
=> Read package info from json file

nixio/data_array.py, nixio/test/test_data_array.py
Numerical types are checked against the numbers.Integral abstract base class, which should match any integer type (including NumPy types).
NumPy types are only currently supported with the h5py backend, so we only test those in the Python version.
=> Use isinstance() for index type checks in DataArray

nixio/pycore/tag.py
Followup to #281. Same rules apply to Tags and MultiTags: Units can be arbitrary strings but retrieve data doesn't work if DataArray and Tag units are unknown.
=> Allow non-SI units in Tags and MultiTags

nixio/pycore/h5dataset.py, nixio/test/test_data_array.py
A relatively simple fix for the multidimension indexing/slicing issue (see #296).
The problem was in the dimensionality "fixing" that I had written for the cases where the number of dimensions to be returned were fewer than the number of dimensions of the underlying data. The old fix relied on padding dimensions and made incorrect assumptions about why the data dimensions didn't match.
Now we use the count tuple to set the shape of the data, since count always matches the shape of the data to be read. The returned data is then reshaped prior to returning from the function to fit the requested data shape.
I added a test, copied from @adityachivu's example in the issue.
=> Fix for data indexing and slicing

MANIFEST.in, nixio/__init__.py, nixio/block.py, nixio/compression.py, nixio/file.py, nixio/pycore/block.py, nixio/pycore/data_array.py, nixio/pycore/file.py, nixio/pycore/h5dataset.py, nixio/pycore/h5group.py, src/PyBlock.cpp, src/PyFile.cpp, src/transmorgify.hpp
This PR adds compression support for data.
Counterpart to G-Node/nix#695.
Some notes:
- I created a Compression class to work as a "fake enum". It's just a static class with the three members as strings. I did this for consistency with the other enums like LinkType and DataType and because it's simpler for passing them into the bindings as strings. I'm planning on turning these into proper enums at some point (when the bindings are removed at the latest).
- I didn't bother to make a proper "converter" for the enum in the bindings. There's just a function (defined in transmorgify.hpp) that does a one-way conversion from the Python string to the appropriate nix::Compression enum value.
- I followed the way the global option works in NIX: If a file is opened with compression on and the data …
=> Data compression

nixio/data_array.py, nixio/test/test_data_array.py
`DataSet.__getitem__` checks if the indexes or slices are out of bounds before calling the `read_data()` methods, in order to throw a more useful error message.
Fixes #299.
=> Catch out of bounds indexing errors in datasets

appveyor.yml, nixio/__init__.py, nixio/pycore/data_array.py, nixio/pycore/data_set.py, nixio/pycore/data_view.py, nixio/pycore/dimensions.py, nixio/test/test_data_array.py, setup.py
This PR brings the ability to retrieve a data slice from a DataArray based on either indexes (like regular slicing) or based on the dimensional data of the array. The method is currently called `get_slice()` but I'm open to suggestions for renaming it. I'd also rename the accompanying enum, `DataSliceMode`, to match whatever we end up calling the method, if we do rename it.
There's a small test that's based on [my comment](https://github.com/G-Node/nixpy/issues/298#issuecomment-397801984) from the issue where we talked about this feature. Have a look at that and let me know if I missed anything.
Also, as discussed, the method returns a DataView. This required splitting out the definition of the DataSet from the data_array file.
A small fix is also included in this PR: The …
=> Slice data by index or dimensional data

.travis.yml, appveyor.yml, nixio/test/test_block.py, nixio/test/test_data_array.py, nixio/test/test_dimensions.py, nixio/test/test_feature.py, nixio/test/test_file.py, nixio/test/test_group.py, nixio/test/test_multi_tag.py, nixio/test/test_property.py, nixio/test/test_proxy_list.py, nixio/test/test_section.py, nixio/test/test_source.py, nixio/test/test_tag.py, nixio/test/xcompat/writefullfile.cpp
Another small round of test cleanup. I've removed the C++ test subclasses that would test the bindings, since they're no longer valid in this branch.
I'm also re-enabling the macOS NIX compatibility tests since we've found the issue. They should pass as soon as the NIX fix is merged.
=> Remove C++ (HDF5 backend) tests

nixio/file.py
Throw warning that backend specification is deprecated.
I'm adding this to avoid breaking scripts and the Neo NixIO when the new version eventually lands, at least for a while.
=> Ignore old backend argument

.travis.yml, nixio/block.py, nixio/container.py, nixio/feature.py, nixio/file.py, nixio/hdf5/h5dataset.py, nixio/hdf5/h5group.py, nixio/multi_tag.py, nixio/section.py, nixio/source.py, nixio/test/test_container.py, nixio/test/test_file.py, nixio/test/test_section.py
When objects can be referenced from multiple locations (e.g., a LinkContainer in a Group, a Source in a data object's `sources`, an object's `metadata`, etc), removing them requires scanning through the tree for references to the same object and deleting them. This PR adds a `delete_all` method to the `H5Group` backend class and uses it through the `__delitem__` methods in the Container class and its derivatives. The `delete_all` method scans through the HDF5 file and removes all groups which match a given set of entity IDs.
The `__delitem__` methods have slight variations depending on the type of Container:
- In the base **Container** class, it simply scans the object tree, starting from the parent Block, and deletes all references to the object being deleted.
- In the …
=> Delete all references when deleting objects from primary Container

nixio/dimensions.py, nixio/test/test_dimensions.py
DimensionContainer failed to set the dimension properly when
initialising a Dimension that was being loaded from the file. It was
looking for an "index" attribute and was returning None. Should be using
the name of the HDF5 Group object.
Added tests to catch regressions.
Wrapping index in int() when returning and when setting the object
attribute to catch unwanted behaviour.
=> Bugfix: Set dimension.index properly on __init__

.travis.yml, nixio/section.py, nixio/test/xcompat/compile.py, scripts/dorelease.py
Allow Sections to be created without specifying a `type` property. This will give the Section the default type string `"undefined"`, which is the same behaviour as in odML.
Additional changes are for compiling and running crosscompatibility tests with C++ NIX.
=> Default Section type

nixio/multi_tag.py, nixio/test/test_multi_tag.py
1D position arrays are handled as a special case. This used to work
before because the DataArray would allow indexing with more indexes than
the length of the array itself. The new DataArray indexing function
doesn't allow this and tries to follow numpy array indexing rules.
Test added to catch regression.
=> Fix for retrieve_data when MultiTag positions array is 1D

nixio/pycore/dimensions.py, nixio/test/test_dimensions.py
* fix axis function to work properly if count and start index are given
* ensure that index_of returns an int. previously this ``` array[dim.index_of(1.0) : dim.index_of(2.0)]``` did not work without  casting to int
=> tiny fixes to SampledDimenision util functions

nixio/container.py, nixio/data_view.py, nixio/dimensions.py, nixio/property.py, nixio/section.py, nixio/test/test_nix_compatibility.py, nixio/util/units.py, nixio/validate.py
Counterpart to PR #339 (same fix in v1.4). The calculation for the axis of a sampled dimension was ignoring the start value.
=> [dev] SampledDimension.axis bug fix

nixio/pycore/section.py, nixio/pycore/util/units.py
Importing abstract base classes directly from collections will cause an
error in Python 3.8. Currently, in 3.7, it raises a warning. In 3.8,
they will have to be imported from collections.abc.
Wrapping in exception catcher for compatibility with older versions.
=> [v1.4] Change collections ABC imports to new module

nixio/block.py, nixio/data_frame.py, nixio/test/test_data_frame.py, nixio/test/test_nix_compatibility.py, nixio/test/xcompat/readdataframes.cpp, nixio/test/xcompat/readfullfile.cpp, nixio/test/xcompat/writefullfile.cpp
I add the basic ones for DFs in the test_full_file and test_full_file_read functions.
So, basic write and read compatibilities are checked.
Please suggest any further test needed.
=> Dataframe compatibility test

nixio/test/test_validator.py, nixio/validate.py
Refering to #369 
The original way of validating labels and ticks in nixpy validator is not correct, now it is fixed.
=> Fix the Bug in Validating Dimensions

docs/source/examples/multipleROIs.py, docs/source/examples/spikeFeatures.py, docs/source/examples/untaggedFeature.py, docs/source/overview.rst, docs/source/tutorial.rst, nixio/data_array.py, nixio/multi_tag.py, nixio/tag.py, nixio/test/test_multi_tag.py, nixio/test/test_tag.py
Dropping `retrieve_` prefix from data access methods in Tag and MultiTag:
- `retrieve_data` → `tagged_data`
- `retrieve_feature_data` → `feature_data`
Closes #372
=> Retrieve rename

nixio/block.py, nixio/data_array.py, nixio/data_frame.py, nixio/entity.py, nixio/file.py, nixio/section.py, nixio/source.py, nixio/validate.py
Add the descriptions  to the DataFrame and Validator methods and properties. 
Add the link to metadata for DataFrame 
Delete the __eq__ and __hash__  for some objects and their parent Class entity already have the exactly same method.
=> Docstrings for DataFrame and Validator

README.rst, appveyor.yml
Since we created the G-Node user on Appveyor and moved all official builds to that user, badges and links should be taken from that build. The NIX artifact URL isn't currently used in the appveyor.yml, but it will once we get compatibility tests working on Windows.
=> Change all Appveyor URLs to point to G-Node builds

nixio/section.py, nixio/test/test_section.py
Found (and fixed) a bug in the inverse search when there were objects in the file that did not have a metadata link.
=> Inverse search fix

nixio/block.py, nixio/file.py, nixio/hdf5/h5group.py, nixio/section.py, nixio/test/test_block.py, nixio/test/test_file.py, nixio/test/test_section.py, nixio/util/util.py
Refer to the Issue #367 
This PR adds a function on the entity level to allow copying NIX objects between files. This copy is recursive and the data in the objects is also carried over.
The UUID will always be carried over.
Definitely need some tests.
How should one deal with the links to the group in the block is opened to discussion. (I have never tried just copying a non-empty group without copying the contents in the block)
=> Copy function for all entities

nixio/data_array.py, nixio/data_frame.py, nixio/entity.py, nixio/feature.py, nixio/file.py, nixio/multi_tag.py, nixio/section.py, nixio/tag.py
Refer to the issue #368 
I added a flag for timestamp updating when the file is opened. 2 functions (time_auto_update_on() and time_auto_update_off()) are added for altering the flag after the file is opened.
The current policy is to update the time whenever a property of an Entity or File is changed and when the time_auto_update flag is True. I do not put the flag in the force_update_at() function because it is more flexible this way. Note that the update of metatdata will not change the update_at() time anyway.
The force_update_at() in creation is not affected.
As of the performance issue, the time used for changing the expansion_origin for data_array 100,000 times is:
**EDITED:**
always update (without a flag): around 45s
flag = True: around 45s (possibly slower for sections or …
=> Add auto-time-update flag to NIXpy file

nixio/property.py, nixio/test/test_property.py
=> [Property values] Add append_values method for modifying values

docs/source/overview.rst
Original docs contain outdated sample code concerning metadata
=> Update old style Values in the docs

nixio/feature.py, nixio/tag.py
=> [enum] Add lower() to linktype in lt setter and fe creation to support old strings

docs/source/install.rst
- Moved installation instructions to the top since it's the most
important part and, for most users, the only piece of information they
care about.
- Dependencies moved to the end.  Users don't need this information
unless they're building from source (and even then, the pip method would
install them automatically).
- Changed dependency URLs to their PyPI page.  If users need to install
these manually, the PyPI page is more relevant.
- Added note to dev/beta version installation instructions that this
version should be used for testing new features.
=> [docs] Reordering and minor rewrite of install page

nixio/feature.py, nixio/tag.py
Refer to Issue #389.
As suggested in #389, the features should not have the attribute name. Also, feature should not have type_ and definition attributes. Its string representation should also be different. Therefore, this PR remove the base class entity.
As an result,
- Feature will not have name, type, definition attributes anymore
-  The __contains__ method of feature container will not use the feature.name
- create_at and update_at property is kept and moved to feature 
- Change the feature string repr to showing data.name and link_type
=> [feature] Change base class from Entity to object

nixio/data_frame.py
Currently accessing the columns property when some values in df.units are None throws an Error.
This PR fixes the bug
=> [df]Fix bug of getting column property when some unit is None

nixio/property.py
Refer to Issue #364 
Originally, when reading values (getting props.values) from file with version < 1.1.1, it will return an old style compound type with (v.value, v.uncertainty, v.reference, v.filename, v.encoder, v.checksum). 
I break it down for value, uncertainty and reference. All now returns a tuple for values, single value for reference and uncertainty.
The problem is we cannot distinguish between an empty str or 0.0 and an unsetted uncertainty or reference.
=> [prop] Add function to read old Values (incl. uncertainty, reference)

.travis.yml, nixio/data_set.py, nixio/datatype.py, nixio/property.py, nixio/test/test_data_array.py, nixio/test/test_nix_compatibility.py, nixio/test/test_property.py, nixio/test/xcompat/readfullfile.cpp, nixio/test/xcompat/writefullfile.cpp, nixio/util/util.py, setup.py
Fixed support for Unicode in Property values and added tests for Property and DataArray data.
When writing values, string types are run through ensure_text.  In Python 3 this converts to `str` and for Python 2 it converts to unicode.
When reading values, bytes are run through ensure_str.  In Python 3 this converts to str and for Python 2 it converts to basestring.
Added new test `test_unicode_values`.  The `ensure_str` conversion is replicated here to cover the case for Python2.
No write conversions are necessary since they're taken cafe of by the numpy array type.  The read conversion occurs in the same way as for the Property values, but in this case, it's returned as a numpy array with the vlen_str_dtype.
Added new test `test_array_unicode`.
Unicode property values and DataArray data …
=> Support unicode in Property values

.travis.yml
Fixes macOS python 3 build on Travis.
=> [travis] macOS python3: Prefix path

nixio/property.py, nixio/section.py
Refering to #429 
The sizes before and after, given chunk=True and compression=auto, are 454mb and 225mb.
=> Add shape when initializing properties to optimize storage

nixio/hdf5/h5group.py
Originally the function won't work, now we can get nix Blocks or Sections from h5group. Probably need some test
=> Fix bug for h5group.root

nixio/data_array.py, nixio/dimensions.py, nixio/test/test_dimensions.py
Refer to #439 and comments in #430
=> Add docstrings for the DataFrameDimension related methods

nixio/block.py, nixio/exceptions/exceptions.py, nixio/multi_tag.py, nixio/test/test_multi_tag.py
Also for extents.
Referring to #418, #789.
Also add some test for this constructor.
=> Allow supplying np_arrays or list for multi_tags positions

nixio/block.py, nixio/test/test_data_frame.py
Add test for creation of dataframe without column names and directly from a np compound array.
Fix a bug with string for such kind of creation.
=> Fix bug when create dataframe from compound arrays and add test

nixio/block.py, nixio/multi_tag.py, nixio/test/test_data_frame.py, nixio/test/test_multi_tag.py, nixio/test/test_tag.py
Followup to #444.
Codestyle fixes and unnecessary lambda removal.
A few snuck in while the previous PR was open.
@hkchekc Have a look at this PR and note the changes in the `assertRaises()` calls.  I went through and changed all the old ones I had written too so they don't use `lambda` since we can pass arguments to the callable.
There are a few `assertRaises()` calls that use lambda because they're testing indexing failures, so the arguments don't work exactly there.  We could also use `with self.assertRaises(<ErrorType>)`, but for now this should be good enough.
=> Codestyle fixes

MANIFEST.in, nixio/cmd/__init__.py, nixio/cmd/upgrade.py, nixio/cmd/validate.py, nixio/file.py, nixio/property.py, nixio/test/test_file.py, nixio/test/test_validator.py, nixio/validator.py, scripts/README.md, setup.py
This PR is mainly for the upgrade script but also includes some fixes and cleanup.
The script first checks the file header version to see if it's older than the current. If it is, it continues to collect tasks that need to be performed to complete the upgrade.
Tasks are created using functions that check if a change is required and if so, they return a closure bound to the specific filename. The returned function is then run after the user confirms they want to apply the changes. If --force is specified, the changes are applied without prompting.
All checks and changes are made in standalone functions that open the file using h5py and close it immediately after. This makes each change atomic (or atomic-ish) and reduces the chances that a file will be left in an invalid state. There's …
=> Upgrade script

nixio/block.py, nixio/container.py, nixio/data_array.py, nixio/data_frame.py, nixio/dimensions.py, nixio/entity.py, nixio/feature.py, nixio/file.py, nixio/group.py, nixio/hdf5/h5group.py, nixio/multi_tag.py, nixio/property.py, nixio/section.py, nixio/source.py, nixio/tag.py, nixio/test/test_container.py, nixio/test/test_data_array.py, nixio/test/test_data_frame.py, nixio/test/test_feature.py, nixio/test/test_file.py, nixio/test/test_multi_tag.py, nixio/test/test_section.py, nixio/test/test_tag.py, nixio/test/test_validator.py
Every object that subclasses Entity now holds a reference to the nix.File object that they belong to.  This reference is the same object for all.  The reference is useful for a few reasons but more recently it becomes necessary for being able to read the `auto_update_timestamps` option, which is a session option only (it's not stored in the file) and is only available through the original File object.
Fixes #460
Changes in this PR:
- The timestamp update option, introduced in PR #385 has been renamed to `auto_update_timestamps`.  When enabled, it updates the `updated_at` timestamp for an object when one of its properties are changed.
- The option is now **ENABLED** by default.  The thought behind having an option to disable the timestamp was that fast creation and/or editing of a large …
=> File references

nixio/datatype.py, nixio/property.py
- Added DataType groups (integers and floats) to simplify data type detection and mapping.
- Small fixes for mapping between odML and NIX property DataTypes.
- DataType.get_dtype() returns Double for all floating point values (see #463).
=> Fixes and simplifications for DataTypes and DataType mappings

.travis.yml, nixio/block.py, nixio/data_array.py, nixio/data_frame.py, nixio/dimensions.py, nixio/file.py, nixio/section.py, nixio/test/test_data_array.py, nixio/test/test_dimensions.py, nixio/test/test_multi_tag.py, nixio/test/xcompat/compile.py, nixio/util/units.py, nixio/validator.py
Implements DimensionLink as discussed in G-Node/nix#824 (closes #466).
Some notes and points for discussion:
- The name of the link in the backend (inside the HDF5 file) is simply `link`.  Therefore, a dimension with a linked object has the following path:
`/data/<block name>/data_arrays/<array name>/dimensions/<dim number>/link/<linked object id>`
- The dimension link object holds an attribute that specifies the type of the object it's linking.  The value of the attribute is either "DataArray" or "DataFrame".
- The dimension module has no access to the DataFrame and DataArray classes so it can't return or initialise an object of those types.  We could do it for the DataFrame, but importing DataArray would result in an import cycle.  DataArrays need to be able to create Dimensions, so …
=> Dimension links

nixio/test/test_data_frame.py
DataFrames in Python2 require ordered dictionaries.
=> Fix DataFrame tests for Python2

nixio/data_array.py, nixio/dimensions.py, nixio/hdf5/h5group.py, nixio/test/test_dimensions.py
When setting the ticks of a RangeDimension that has an object link (DataArray or DataFrame), the object is unlinked.
When linking a data object to a RangeDimension that has ticks, the ticks are removed.
Closes #476.
=> RangeDimension: Replace ticks with link and vice versa when setting

.travis.yml, appveyor.yml, nixio/block.py, nixio/data_frame.py, nixio/hdf5/h5dataset.py, nixio/test/test_data_array.py, nixio/test/test_data_frame.py, nixio/util/util.py
This PR takes care of [recent changes to string handling in H5Py](https://docs.h5py.org/en/stable/strings.html) as well as some older inconsistencies with string handling.
- Use the h5py string_dtype with explicit UTF-8 encoding, instead of a numpy type.
- Write empty string in place of `None` for DataFrame.units: `None` is no longer a valid element of a string array in h5py.
- Change DataFrame tests to check for bytes instead of strings in returned data.
Copying commit message for DataFrame string/bytes element type tests:
String data and attributes in NIXPy are generally returned as strings.  H5Py returns string data from a file as bytes and these are decoded to strings before returning to the user.  Unfortunately, there's no clean way to do the same with compound data types that …
=> H5Py string handling changes and fixes

nixio/data_view.py, nixio/test/test_multi_tag.py
Instead of reading from the underlying DataSet object's _read_data(), call the linked data object's method.  In the case of a DataArray, this will apply polynomial coefficients and the expansion origin to the data slice before returning.
Test added for retrieving data with coefficients and expansion origin through a MultiTag.
Fixes #482.
=> [DataView] Use data object's _read_data()

nixio/block.py, nixio/data_frame.py, nixio/data_set.py, nixio/hdf5/h5dataset.py, nixio/property.py, nixio/tag.py, nixio/test/test_data_frame.py, nixio/test/test_property.py, nixio/test/test_tag.py
Changes the way strings are handled in DataFrame columns.
The core change is in H5DataSet, where the `read_data()` method checks for two cases:
- if the dtype of the data coming from disk is `vlen_str_dtype` (`h5py.string_dtype(encoding='utf-8', length=None)`), then it decodes all the data to Python string (from bytes) using `ensure_str()` from the six package (for Python 2 compatibility).
- if the dtype has `fields` (struct/compound dtype), the fields are iterated and any `vlen_str_dtype` columns are decoded like above.
Similarly, if the dtype of a dataset is requested, it returns `DataType.String` (`np.unicode_`).
Moving the string conversion down into the H5DataSet class is moreappropriate:
- The data type conversion is HDF5-specific: We convert the dtype of string objects from disk …
=> DataFrame string columns

nixio/data_array.py, nixio/hdf5/h5dataset.py, nixio/multi_tag.py, nixio/test/test_data_array.py
Retrieving a single index from a DataArray returns a NumPy array with length 1.
This is inconsistent with NumPy and Python convention but makes general behaviour more consistent, i.e., indexing or slicing a DataArray *always* returns an array.
Fixes #275.
=> Data retrieval fixes and tests

nixio/__init__.py, nixio/data_view.py, nixio/dimensions.py, nixio/multi_tag.py, nixio/tag.py, nixio/test/test_dimensions.py, nixio/test/test_multi_tag.py, nixio/test/test_tag.py
This PR implements the slicing rules described in https://github.com/G-Node/nix/blob/master/docs/slicing_and_indices.md.
Slicing is by default excludes the right endpoint now.  The endpoint can be included by specifying `stop_rule=nix.SliceMode.Inclusive` in the `tagged_data()` method of a Tag or MultiTag.
To clarify, the new Exclusive rules work as follows:
- The first element in the DataView returned by `tagged_data` is the value at the last index of each dimension that is **less than or equal to** the Tag's `position`.
- The last element in the DataView returned by  `tagged_data` is the value at the last index of each dimension that is **less than** the Tag's `position+extent`.
Using Inclusive changes the second behaviour of the last element to be the same as for the first element:
- …
=> Tag retrieval: Inclusive and Exclusive stop rule

.github/workflows/pythonpackage.yml, .gitignore, .travis.yml, README.rst, appveyor.yml
This PR moves builds from travis to github actions.
- the `gh/actions` workflow now runs tests in an os [Linux, MacOS, Windows] Python [3.6, 3.7, 3.8, 3.9] matrix .
- dependent on this test build, the`gh/actions` workflow builds an os [Linux, MacOS, Windows] Python [3.8] matrix using miniconda to make sure anaconda installations on all OS work without issue.
- also dependent on the test build, the `gh/actions` workflow runs coverage builds on Linux with Python 3.8 and for both `codecov` and `coveralls` and pushes the results to the respective services.
- the `gh/actions` workflow also adds a timed build, now running `gh/actions` once a month.
- the travis build is significantly reduced and now includes only a singe Linux build with Python 3.8 and a single allow failures build for the …
=> Github actions update

appveyor.yml, nixio/source.py, nixio/test/test_source.py
this pr addresses issue #498. 
* adds a ``parent_block`` property to the source which is needed to finding referring objects
* adds an explicit ``parent_source`` property (which at the moment performs a search on the sources tree)
* it **does not** change the behaviour of the ``referring_objects`` methods. They will still only return those objects that link directly to the source. That is, calling ``referring_data_arrays`` on a parent source will so far not collect the *DataArrays* of the child sources. I would like to leave this open for discussion. Since these are properties, there is no way of overloading with a default argument. For the time being, this needs to be done on the user side. We may want to discuss this at some point.
=> quick fix for parent block access  on sources

.github/workflows/pythonpackage.yml, appveyor.yml, docs/source/examples/imageData.py, docs/source/examples/imageWithMetadata.py, docs/source/examples/multipleTimeSeries.py, docs/source/examples/regularlySampledData.py, docs/source/examples/singleROI.py, docs/source/examples/spikeFeatures.py, docs/source/examples/spikeTagging.py, nixio/test/test_doc_examples.py, setup.py
This PR introduces tests for the documentation examples in the `docs` folder. Since `docs` resides outside the nixio package, the testing requires executing the example files directly, copying the required 'lenna.png' image from the docs folder and cleaning up created test nix files once the tests are done. Running and cleanup works, please comment if there are any reservations to the way these tests are run or if individual tests should not be excluded.
Running tests for these examples requires the additional packages `matplotlib, scipy, pillow` to be installed. These packages have been added to the `setup.py: tests_requires` and the CI config files.
All plots are rendered non-blocking and are closed after the tests are done. The examples "imageData.py" and "singleROI.py" will open an …
=> Add documentation examples tests

nixio/data_array.py, nixio/dimensions.py, nixio/test/test_dimensions.py
Currently `append_set_dimension` fails if a non-list object, e.g. numpy array, is provided as labels. For convenience it would be nice to accept any object that can be converted to a list. The same is in principle true for Dimension ticks, but here no check on the input type is currently performed.
=> Allow for list-like labels of SetDimension

nixio/dimensions.py, nixio/file.py, nixio/info.json, nixio/test/test_dimensions.py
as we discussed, this pr adds a label for SetDimensions 
As this is a non-breaking change to the model the file format version is increased to 1.2.1
=> Set dim label

nixio/data_view.py, nixio/dimensions.py, nixio/exceptions/__init__.py, nixio/exceptions/exceptions.py, nixio/multi_tag.py, nixio/tag.py, nixio/test/test_data_view.py, nixio/test/test_dimensions.py, nixio/test/test_multi_tag.py, setup.py
This PR changes the way ranges along a dimension are calculated. 
* allows DataView to be invalid and reading access will return an empty array
* range calculation is delegated to the dimensions respecting the SliceMode.
* allows for some simplification of the BaseTag._calc_data_slice method
* We do not necessarily return at minimum a single value along a given dimension. If there are no data points between start and end position the range is invalid and the DataView will become invalid and return an empty array. Just like slicing a numpy array that does not return a result. 
* Invalid DataViews return no data extent, write access will raise an exception. They offer a "debug message" containing the reason of their invalidity.
* I might be that I went a little far with removing the OOB and …
=> Allow DataViews to become invalid fixes #502

nixio/hdf5/h5dataset.py, nixio/hdf5/h5group.py, nixio/test/test_data_view.py
With https://github.com/G-Node/nixpy/commit/b3c21c3efdb48de853a49ad8f0f930457283f280 we fixed the reading of 2D string data. Unfortunately, this implicitly converted python strings to np.str_. With this pr, we keep them as python strings.
fixes #534
=> Keep string data as python str

docs/source/examples/imageWithMetadata.py, docs/source/examples/multipleTimeSeries.py, docs/source/examples/singleROI.py, docs/source/examples/taggedFeature.py
With python2 deprecation, it should be safe to enforce use of the python3 shebang everywhere.  Besides, there can be inconsistencies between distributions, and even system configuration within a single distribution, on whether to ship python as python2, as python3, or not at all.
=> d/s/examples/*.py: use python3 in shebang.

docs/source/examples/lif.py, nixio/block.py, nixio/container.py, nixio/data_frame.py, nixio/data_set.py, nixio/datatype.py, nixio/dimensions.py, nixio/entity.py, nixio/feature.py, nixio/file.py, nixio/hdf5/h5dataset.py, nixio/hdf5/h5group.py, nixio/property.py, nixio/section.py, nixio/source.py, nixio/tag.py, nixio/test/test_data_array.py, nixio/test/test_data_frame.py, nixio/test/test_nix_compatibility.py, nixio/test/test_validator.py, nixio/test/tmp.py, nixio/util/find.py, nixio/util/units.py, nixio/util/util.py, nixio/validator.py
Hi !
I saw this new package in Debian today popping up in my QA list.
Here's a cleanup of Python2 code.
@emollier : please remove python3-six dependency when a new release is published, or I'll do if I notice first
https://tracker.debian.org/pkg/python-nixio
https://salsa.debian.org/detiste-guest/python3-six-removal/-/commit/b3218f61adb31c09cac2de735fd83997abe9b707
=> remove Python2 crumbs

.pylintrc, nixio/hdf5/h5dataset.py, nixio/property.py, scripts/dorelease.py, setup.py
Hi,
This is follow-up to https://github.com/G-Node/nixpy/pull/541 I forgot to do.
@emollier
=> finish six removal

docs/source/conf.py
Since Sphinx 8.0, support for the old intersphinx_mapping format has been removed.  Attempts to build the documentation result in the following errors:
Running Sphinx v8.1.3
loading translations [en]... done
making output directory... done
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
ERROR: Invalid value `None` in intersphinx_mapping['http://docs.python.org/']. Expected a two-element tuple or list.
ERROR: Invalid value `None` in intersphinx_mapping['http://docs.scipy.org/doc/numpy']. Expected a two-element tuple or list.
This change migrates intersphinx_mapping to the new format.
This has been initially reported as [Debian bug #1090153].
[Debian bug #1090153]: https://bugs.debian.org/1090153
=> d/s/conf.py: move to modern intersphinx_mapping.
