- src/PyProperty.cpp
- src/PyValue.cpp
> [→ nix] DataTime, Date removed from DataType

- LICENSE
> LICENSE: changed to BSD 3-clause

- docs/source/install.rst
> Installation guide

- setup.py
This should hopefully fix gh issue #139
> [setup] OSX: select correct boost_python lib

- src/PyDataSet.cpp
> [DataSet] cast void * to char *

- nix/data_array.py
- nix/test/test_data_array.py
> DataSet: implement __iter__ (& simple test case)

- findboost.py
- setup.py
> Try harder to find boost python

- .travis.yml
- CMakeLists.txt
- cmake/FindNIX.cmake
The cmake support is mainly for IDE support (CLion 1.5 has python support).
Travis upgrade to make build (start) faster.
> Upgrade travis to trusty and add a cmake support

- README.md
Made a section on how to install nixpy on OSX.
Fix small typos.
> README: Add OSX Getting Started Guide

- docs/source/overview.rst
-import is required here.
-Travis was passing tests because it may be imported somewhere else.
-it is required for the beginners who are just starting the project
> import numpy in a block in overview.rst

- nixio/file.py
- nixio/group.py
- nixio/pycore/block.py
- nixio/pycore/data_array.py
- nixio/pycore/entity.py
- nixio/pycore/entity_with_metadata.py
- nixio/pycore/entity_with_sources.py
- nixio/pycore/file.py
- nixio/pycore/group.py
- nixio/pycore/multi_tag.py
- nixio/pycore/property.py
- nixio/pycore/section.py
- nixio/pycore/source.py
- nixio/pycore/tag.py
- nixio/pycore/util/util.py
- nixio/section.py
- nixio/test/test_file.py
- nixio/test/test_group.py
- nixio/test/test_section.py
- nixio/util/find.py
Adding Group and Section classes to pycore.
Entity classes have been reorganised a bit to solve issues with import cycles.
TestGroup and TestSection tests all pass, except `test_section_properties` which fails since the Property class isn't implemented yet.
Section tests in TestFile have been enabled again and are passing.
> Python Group and Section classes

- .travis.yml
- nixio/pycore/entity_with_sources.py
- nixio/pycore/h5group.py
- nixio/pycore/section.py
- nixio/pycore/tag.py
Now using creation order when accessing elements by index, same as G-Node/nix#618.
PR also includes a number of bug fixes.
> Creation order indexing

- release_instructions.md
Release instructions for nixpy.
> Release instructions/checklist

- .travis.yml
- README.rst
- appveyor.yml
- nixio/info.py
- nixio/pycore/exceptions/exceptions.py
- nixio/pycore/file.py
- nixio/pycore/util/util.py
- nixio/test/test_file.py
- setup.py
File format version checking and tests.
> V1.2.1 Version checks

- nixio/pycore/block.py
- nixio/pycore/data_array.py
- nixio/pycore/entity.py
- nixio/pycore/entity_with_metadata.py
- nixio/pycore/entity_with_sources.py
- nixio/pycore/feature.py
- nixio/pycore/file.py
- nixio/pycore/group.py
- nixio/pycore/multi_tag.py
- nixio/pycore/property.py
- nixio/pycore/section.py
- nixio/pycore/source.py
- nixio/pycore/tag.py
- nixio/test/test_file.py
- nixio/test/test_section.py
- nixio/test/test_source.py
- src/PySection.cpp
- src/PySource.cpp
Implements inverse search:
- from metadata Sections to Blocks, Groups, DataArrays, Tags, MultiTags, and Sources.
- from Sources to DataArrays, Tags, and MultiTags.
To accommodate this, every object now maintains a reference to its direct parent at all times.
> Inverse search from Sections and Sources

- nixio/pycore/property.py
- nixio/pycore/section.py
- nixio/value.py
which is one of the features people here are missing because it is so hard to browse the tree manually. I just punched it into the pycore files and need some ideas, feedback
So far it uses print but one could probably  think of more elegant ways.
Don't be shy!
> add a metadata printing functionality

- nixio/block.py
- nixio/compression.py
- nixio/data_array.py
- nixio/file.py
- nixio/test/test_compression.py
Fixes compression flag inheritance from File > Block > DataArray.
Added tests for all flag combinations.
> Compression fixes

- nixio/data_array.py
- nixio/dimensions.py
- nixio/test/test_dimensions.py
Some fixes and enhancements for dimension handling:
- The `labels` property can be resized in `SetDimension` #330
- The `ticks` property can be resized in `RangeDimension` #330 
- All dimension properties can be set on creation (append) #331
Tests included
> Dimension fixes and enhancements

- nixio/property.py
- nixio/section.py
added the pprint() function for no-bindings-dev's property (metadata)
> Pretty Print for no-bindings-dev

- .travis.yml
- nixio/property.py
Always convert uncertainty to float for compatibility with odML
> [property] Force "uncertainty" to float

- nixio/compression.py
- nixio/exceptions/exceptions.py
- nixio/file.py
- nixio/property.py
- nixio/section.py
- nixio/test/test_compression.py
- nixio/test/test_container.py
- nixio/test/test_dimensions.py
- nixio/test/test_section.py
- nixio/test/test_validator.py
- nixio/validate.py
Pretty big, but it's all just PEP8 and cleanup.
> PEP8 fixes, clear unused variables, and remove star imports

- .travis.yml
- nixio/__init__.py
- nixio/block.py
- nixio/compression.py
- nixio/container.py
- nixio/data_frame.py
- nixio/data_set.py
- nixio/data_view.py
- nixio/dimensions.py
- nixio/exceptions/exceptions.py
- nixio/file.py
- nixio/multi_tag.py
- nixio/property.py
- nixio/section.py
- nixio/test/test_compression.py
- nixio/test/test_container.py
- nixio/test/test_data_frame.py
- nixio/test/test_dimensions.py
- nixio/test/test_multi_tag.py
- nixio/test/test_nix_compatibility.py
- nixio/test/test_section.py
- nixio/test/test_validator.py
- nixio/util/units.py
- nixio/validate.py
It is a incomplete draft for the dataframe object in NIXpy with basic read/write functions. Therefore, it will still be a lot of changes. I create this pull request mainly for:
- finding out any fundamental incorrect idea about a dataframe
- discovering any important incompatibility with the C++  NIX
- finding out any necessary attributes that I missed out
- discussion of any possible new feature
The following changes is in my schedule:
-  make append_column and write_to_csv functional
- support indexing columns (now one can only find columns with name)
- make write column function more efficient
- support tuples/list/arrays for col_names/col_dtype/unit in create_new function (now only support dict)
- write the test for dataframe
- fixing bugs with writing/ appending/ reading multiple …
> Dataframe object for nixpy

- nixio/data_frame.py
add two functions to export Nixpy dataframes to panda dataframe and csv file
> [DataFrame] write_to_csv and write_to_pandas

- nixio/block.py
- nixio/data_frame.py
support create with list type data,
> support create with list type data

- nixio/block.py
- nixio/data_frame.py
- nixio/test/test_data_frame.py
> Test for DataFrame

- docs/source/index.rst
- docs/source/install.rst
new tutorial for nix no bindings dev. need to build it with sphing and push it to gh-pages
> fixed tutorial pages source

- nixio/block.py
- nixio/test/test_data_frame.py
- nixio/test/test_nix_compatibility.py
I realized numpy strings are not converted to vlen_str.
I fix it in this PR
> Dataframe bug with numpy strings

- nixio/data_frame.py
- nixio/test/test_nix_compatibility.py
- nixio/test/xcompat/readdataarrays.cpp
- nixio/test/xcompat/readdataframes.cpp
for DataFrame and DataArray
write in nixpy and read with nix
test for multitags sources feature etc. will be added later
> add two compatibility tests

- nixio/group.py
data_frame should be appendable to groups
> Add data_frames property to groups

- nixio/block.py
- nixio/dimensions.py
- nixio/group.py
#374
Add a pprint function to the block.
The Data Tree and some small description of each object is printed
> Pretty Print for Data Tree

- nixio/test/test_nix_compatibility.py
- nixio/test/xcompat/readmultitags.cpp
- nixio/test/xcompat/readtags.cpp
as the title.
Will need a rebase if #376 is merged first.
> Add compatibility test for Tags and MultiTags

- readthedocs.yml
Fix the readthedocs build failing.
Install nixio with setup.py
> [readtehdocs] Add yml file to install nixio

- nixio/file.py
1.1.1 format version represents the introduction of the DataFrame data object.
> File format version: 1.1.1

- docs/source/api_data.rst
- docs/source/api_metadata.rst
- nixio/block.py
- nixio/data_set.py
- nixio/property.py
- nixio/section.py
- Delete and Update outdated classes and structures such as Values and pycore.* 
- Add DataFrame API to the docs page
- Add some further docstrings
- Some typo fixes
> Update and fix readthedocs page building

- nixio/block.py
- nixio/file.py
- nixio/section.py
Refer to Issue #374.
Also adjusted section.pprint() a little bit
> Add pprint function for file

- nixio/data_frame.py
- Previously, setting only part of the units to None will raise Error, the problem is solved
- Print_table method now support printing the part of DataFrame
- read_columns method now has an option to group return values in different way
> Some changes to DataFrame API

- nixio/entity.py
> Hide IDs from string representations of entities

- nixio/dimensions.py
In reference to the discussion in #398.
> Change dimension_type.setter to private method

- nixio/block.py
- nixio/container.py
- nixio/data_frame.py
- nixio/dimensions.py
- nixio/entity.py
- nixio/feature.py
- nixio/hdf5/h5group.py
- nixio/property.py
- nixio/section.py
Attempting to address all LGTM.com warnings.
Some will remain, like the warnings about not overriding __eq__ in Entity subclasses.
*Keeping this as draft until #408 is merged*
> Addressing LGTM warnings

- nixio/test/test_validator.py
- nixio/validator.py
NOTE: I should also add a test for this
> [validator] Fix extent dimension match check

- .travis.yml
- nixio/multi_tag.py
- nixio/tag.py
- nixio/test/test_multi_tag.py
- nixio/test/test_tag.py
Same functions as https://github.com/G-Node/nix/pull/801 , but for nixpy
> Flexible Tag and MultiTag

- nixio/data_array.py
- nixio/data_frame.py
- nixio/dimension_type.py
- nixio/dimensions.py
- nixio/test/test_dimensions.py
- nixio/validator.py
> New DataArray dimension type: DataFrameDimension

- nixio/dimensions.py
- nixio/test/test_dimensions.py
> Change the search method of index_of() for range_dim

- nixio/data_array.py
- nixio/dimensions.py
- nixio/test/test_data_array.py
> Add method that returns 1-based index dimension iterators

- nixio/block.py
- nixio/exceptions/exceptions.py
- nixio/test/test_data_frame.py
> Enforce unique column names for DataFrame

- docs/source/api/modules.rst
- docs/source/api/nixio.cmd.rst
- docs/source/api/nixio.exceptions.rst
- docs/source/api/nixio.hdf5.rst
- docs/source/api/nixio.rst
- docs/source/api/nixio.test.rst
- docs/source/api/nixio.test.xcompat.rst
- docs/source/api/nixio.util.rst
- docs/source/conf.py
- docs/source/index.rst
- nixio/__init__.py
- nixio/container.py
- nixio/data_array.py
- nixio/data_frame.py
- nixio/dimensions.py
- nixio/exceptions/__init__.py
- nixio/tag.py
- nixio/test/test_block.py
- nixio/test/test_data_array.py
- nixio/test/test_data_frame.py
- nixio/test/test_dimensions.py
- nixio/test/test_file.py
- nixio/test/test_group.py
- nixio/test/test_property.py
- nixio/util/__init__.py
Fixed a bunch of codestyle issues (warnings reported by [pycodestyle](https://pypi.org/project/pycodestyle/) and [pyflakes](https://pypi.org/project/pyflakes/)).  Mostly code styling (indentation, spaces, etc) and imports (unused imports, explicit module-level imports).
This PR also includes autogenerated docs for all the internal modules.  These are included as an extra top-level link in the docs that's titled "for developers".  While generating and reviewing docs, I also fixed a few documentation issues.
> Documentation and codestyle

- .travis.yml
- nixio/info.json
> Use proper version string for dev versions (master branch)

- nixio/cmd/upgrade.py
- scripts/dorelease.py
AliasRangeDimension objects become RangeDimension with link to parent data array.
> Upgrade dimension

- nixio/exceptions/__init__.py
- nixio/exceptions/exceptions.py
- nixio/feature.py
- nixio/multi_tag.py
- nixio/tag.py
- nixio/test/test_feature.py
- nixio/test/test_multi_tag.py
- nixio/test/test_tag.py
This PR adds support for linking DataFrames to Tags via Features.
One thing I'm unclear about is whether it makes sense for all kinds of links.  Would it make more sense to restrict DataFrame linking to specific kinds of linking?
> Support linking DataFrames to Tags via Features

- .travis.yml
> [travis/macOS] switch off brew update
